import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const jsx=(type,props,key)=>typeof type==='function'&&type.name==='DecisionEvidence'?type(props):({type,props:props||{},key});
const nodes=(tree,p=()=>true)=>{const out=[];function visit(n){if(Array.isArray(n))n.forEach(visit);else if(n&&typeof n==='object'&&n.props){if(p(n))out.push(n);visit(n.props.children);}}visit(tree);return out;};
const text=n=>n==null||typeof n==='boolean'?'':Array.isArray(n)?n.map(text).join(' '):typeof n==='object'?text(n.props?.children):String(n);
const orig=(n)=>({id:'event-'+n,action:n?'WAIT':'BUY',publishedAt:'2026-10-07T01:00:00Z',sourceCutoff:'2026-10-07T00:00:00Z',thesis:'Full immutable original thesis '+n,risks:'Original risk '+n,modelIdentity:'model',assessmentId:'assessment-'+n});
const calls=Array.from({length:4},(_,n)=>({callId:'call-'+n,instrument:{id:'stock-'+n,symbol:['AVGO','BEAM','MRVL','NVDA'][n],name:'Share '+n,exchange:'NASDAQ',currency:'USD'},original:orig(n),latestReview:null,lastReviewedAt:'2026-10-07T01:00:00Z',state:'WATCHING',dataStatus:'READY',entry:null,exit:null,pricesAsOf:null,blocker:null,performance:{netReturn:'0.99',benchmarkReturn:'0.5',benchmark:{symbol:'QQQ'}}}));
const researchItems=['1AI','FIG','WA1'].map((symbol,n)=>({instrument:{id:'research-'+n,symbol,name:symbol,exchange:n===1?'NYSE':'ASX',currency:n===1?'USD':'AUD'},original:orig(n+4),latest:orig(n+4),history:[orig(n+4)],sources:[{name:'Saved issuer source',url:'https://example.com/filing',text:'Frozen source text',availableAt:'2026-10-06T01:00:00Z',sourcePublishedAt:null}],priceEvidence:{status:'ABSENT',latestAt:null,latestLoadedAt:null,providers:[],sampleRows:0,availableRows:0,omittedRows:0,caveat:'Benchmark and session support unverified.'},measurementStatus:'NOT_MEASURABLE',measurementBlocker:'No verified venue/benchmark.',includedInPerformance:false}));
const dashboard=()=>({contractVersion:1,items:structuredClone(calls),blockedItems:[],nextCursor:null,blockedNextCursor:null,counts:{trackedCalls:4,callsNeedingAttention:0,blockedWithoutCall:0}});
const status=()=>calls.map(c=>({callId:c.callId,eventId:c.original.id,status:'pending',actionReturn:null,asOf:null,blocker:null}));
function load(file,append,states=[],research={payload:{items:researchItems},loading:false,error:''},client={}){
 let index=0;const writes=[],effects=[];const react={useId:()=> 'research',useState:v=>{const n=index++;return[n in states?states[n]:v,value=>writes.push({n,value})]},useEffect:f=>effects.push(f),useCallback:f=>f,useRef:v=>({current:v})};
 const source=fs.readFileSync(new URL('../components/'+file+'.tsx',import.meta.url),'utf8');const exports={};vm.runInNewContext(ts.transpileModule(source+'\n'+append,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:name=>name==='react'?react:name==='react/jsx-runtime'?{jsx,jsxs:jsx,Fragment:'fragment'}:name.includes('supabase-browser')?{getBrowserSupabase:()=>client}:name.includes('SharedResearchRecommendations')?{default:name,useSharedResearchRecommendations:()=>research}:{default:name},Set,Map,Date,Number,crypto:{randomUUID:()=> 'request'}});return {exports,writes,effects};
}
function render(options={}){
 const p=options.payload===undefined?dashboard():options.payload;const scope=options.scope||'all',h=options.horizon||5,page=options.page||{cursor:null,blocked:null},revision=options.revision||0;
 const key=`${scope}:${page.cursor||''}:${page.blocked||''}:${revision}`,eventKey=(p?.items||[]).map(c=>`${c.callId}:${c.latestReview?.id||c.original.id}`).join('|');
 const states=[scope,h,page,revision,options.selected||null,options.selectedResearch||null,!!options.performanceOpen,!!options.reviewOpen,{warning:false,title:'Ready'},options.loading?null:{key:options.dashboardKey||key,payload:p,error:options.error||''},options.trialLoading?null:{key:options.trialKey||`${scope}:${h}:${revision}:${eventKey}`,items:options.statuses||status(),error:!!options.trialError}];
 const r=load('SharedDecisionWorkspace','export {validActionStatus,latestDecision};',states,options.research,options.client);return {...r,tree:r.exports.default()};
}
const mainTable=tree=>nodes(tree,n=>n.type==='table'&&text(n).includes('Saved AI decisions and selected-horizon action trials'))[0];
test('compact single table combines four pending calls and three excluded research rows',()=>{const {tree}=render();const rows=nodes(mainTable(tree),n=>n.type==='tbody')[0].props.children;assert.equal(nodes(rows,n=>n.type==='tr').length,7);assert.equal(nodes(rows,n=>n.type==='button').length,7);assert.equal((text(rows).match(/Pending/g)||[]).length,4);assert.equal((text(rows).match(/Research only/g)||[]).length,3);assert.equal(text(rows).includes('99.00%'),false);assert.match(text(tree),/7 saved decisions/);assert.match(text(tree),/4 pending on page/);assert.equal(nodes(tree,n=>n.type==='./SharedAIPerformance').length,0);assert.equal(nodes(tree,n=>n.type==='select').length,2);assert.equal(nodes(tree,n=>n.type==='h1').length,1);});
test('all seven arrows route exact latest call event or immutable research item',()=>{const {tree,writes}=render();const buttons=nodes(mainTable(tree),n=>n.type==='button');for(const b of buttons){assert.match(text(b),/›/);b.props.onClick();}const callWrites=writes.filter(w=>w.n===4),researchWrites=writes.filter(w=>w.n===5);assert.equal(callWrites.length,4);assert.equal(researchWrites.length,3);for(const w of callWrites)assert.equal(w.value.eventId,'event-'+w.value.callId.slice(-1));for(const w of researchWrites)assert.equal(w.value.includedInPerformance,false);});
test('analytics is lazy and receives the sole controlled selected horizon',()=>{const closed=render();nodes(closed.tree,n=>n.type==='button'&&text(n).startsWith('Performance details'))[0].props.onClick();assert.equal(closed.writes.at(-1).n,6);const {tree}=render({performanceOpen:true,horizon:20});const perf=nodes(tree,n=>n.type==='./SharedAIPerformance')[0];assert.equal(perf.props.horizon,20);assert.equal(nodes(tree,n=>n.type==='select').length,2);assert.match(text(mainTable(tree)),/20\s*-session trial return/);});
test('scope/horizon/refresh handlers reset page and clear selected drawers',()=>{const {tree,writes}=render();const selects=nodes(tree,n=>n.type==='select');selects[0].props.onChange({target:{value:'watched'}});assert.deepEqual(writes.map(w=>w.n),[0,2,4,5]);assert.equal(writes[0].value,'watched');selects[1].props.onChange({target:{value:'20'}});assert.equal(writes.at(-1).n,1);assert.equal(writes.at(-1).value,20);nodes(tree,n=>n.type==='button'&&text(n)==='Refresh')[0].props.onClick();assert.equal(writes.at(-1).n,3);});
test('review polling remains mounted but hidden and preserves attention affordance',()=>{const {tree}=render();const pipeline=nodes(tree,n=>n.type==='./TradingPipelineStatus')[0];assert.ok(pipeline);assert.equal(pipeline.props.hidden,true);assert.equal(typeof pipeline.props.onStatusChange,'function');nodes(tree,n=>n.type==='button'&&text(n).startsWith('Review status'))[0].props.onClick();});
test('scoped total is full call-cycle count plus research records while pagination remains explicit',()=>{const p=dashboard();p.counts.trackedCalls=12;p.nextCursor='next';const {tree}=render({payload:p});assert.match(text(tree),/15 saved decisions/);assert.match(text(tree),/4\s+call cycles on this page/);assert.match(text(tree),/Scoped counts include other calls pages/);assert.equal(nodes(tree,n=>n.type==='button'&&text(n)==='Next calls').length,1);});
test('obsolete event, stale scope and stale horizon never show paper or old trial return',()=>{const statuses=status();statuses[0]={...statuses[0],eventId:'old-review',status:'matured',actionReturn:'0.9',asOf:'2026-10-01T00:00:00Z'};for(const opt of [{statuses},{trialKey:'watched:5:0:old'},{trialKey:'all:20:0:old'}]){const {tree}=render(opt);assert.equal(text(mainTable(tree)).includes('+90.00%'),false);assert.equal(text(mainTable(tree)).includes('+99.00%'),false);}assert.match(text(nodes(render({statuses}).tree,n=>n.type==='./TradingPipelineStatus')[0]),/No verified result matches/);});
test('error/loading/empty trial paths never manufacture zero or paper-cycle return',()=>{for(const options of [{trialLoading:true},{trialError:true}]){const {tree}=render(options);assert.equal(text(mainTable(tree)).includes('0.00%'),false);assert.equal(text(mainTable(tree)).includes('99.00%'),false);}const p=dashboard();p.items=[];p.counts.trackedCalls=0;assert.match(text(render({payload:p,research:{payload:{items:[]},loading:false,error:''}}).tree),/No saved AI decisions in this scope/);});
test('valid action status rejects wrong horizons, duplicate calls, malformed mature return and absent timestamp',()=>{const {exports}=render();const good={contractVersion:1,horizon:5,items:status()};assert.equal(exports.validActionStatus(good,5),true);assert.equal(exports.validActionStatus(good,20),false);for(const mutate of [p=>p.items.push(p.items[0]),p=>p.items[0].actionReturn='0',p=>Object.assign(p.items[0],{status:'matured',actionReturn:'NaN',asOf:'2026-01-01'}),p=>Object.assign(p.items[0],{status:'matured',actionReturn:'0.01',asOf:null})]){const p=structuredClone(good);mutate(p);assert.equal(exports.validActionStatus(p,5),false);}});
test('latest original/review ordering matches SQL timestamp then UUID',()=>{const {exports}=render();const c=structuredClone(calls[0]);c.original.id='eeee';c.latestReview={...orig(8),id:'dddd',publishedAt:c.original.publishedAt};assert.equal(exports.latestDecision(c).id,'eeee');c.latestReview.id='ffff';assert.equal(exports.latestDecision(c).id,'ffff');c.latestReview.id='aaaa';c.latestReview.publishedAt='2026-10-07T01:01:00Z';assert.equal(exports.latestDecision(c).id,'aaaa');});
test('cancelled trial request cannot publish results into newer scope/horizon',async()=>{let resolve;const promise=new Promise(r=>resolve=r);const r=render({trialLoading:true,client:{rpc:()=>promise}});const cleanup=r.effects[1]();cleanup();resolve({data:{contractVersion:1,horizon:5,items:status()},error:null});await new Promise(r=>setTimeout(r,0));assert.equal(r.writes.filter(w=>w.n===10).length,0);});
test('paper-ready action blocker is visible in review issues independently of paper status',()=>{const statuses=status();statuses[0]={...statuses[0],status:'blocked',blocker:'PINNED_EVIDENCE_REVISED'};const {tree}=render({statuses,reviewOpen:true});const panel=nodes(tree,n=>n.type==='./TradingPipelineStatus')[0];assert.match(text(panel),/PINNED_EVIDENCE_REVISED|pinned evidence revised/i);});
test('research drawer shows locked original/history/sources without inventing notes or trials',()=>{const r=load('SharedResearchRecommendations','',[],undefined);const tree=r.exports.default({item:researchItems[0],onClose:()=>{}});assert.match(text(tree),/Read original reasoning/);assert.ok(text(tree).includes(researchItems[0].original.thesis));assert.match(text(tree),/Locked/);assert.match(text(tree),/Frozen source text/);assert.match(text(tree),/No paper trial or private-note journal exists/);assert.equal(nodes(tree,n=>n.type==='form'||n.type==='textarea').length,0);});
test('verified mature fraction is formatted once; paper-cycle return remains distinct',()=>{const statuses=status();statuses[0]={...statuses[0],status:'matured',actionReturn:'0.125',asOf:'2026-10-07T00:00:00Z'};const {tree}=render({statuses});assert.match(text(mainTable(tree)),/\+12\.50%/);assert.equal(text(mainTable(tree)).includes('99.00%'),false);});
test('missing latest event triggers review attention while genuine pending trials do not',()=>{const complete=render();const completeButton=nodes(complete.tree,n=>n.type==='button'&&text(n).startsWith('Review status'))[0];assert.equal(text(completeButton).includes('Attention'),false);const statuses=status();statuses[0].eventId='obsolete';const missing=render({statuses,reviewOpen:true});assert.match(text(nodes(missing.tree,n=>n.type==='button'&&text(n).startsWith('Review status'))[0]),/Attention/);assert.match(text(nodes(missing.tree,n=>n.type==='\.\/TradingPipelineStatus')[0]),/No verified result matches/);});
test('research hook suppresses stale scope/revision response and stale cached payload',async()=>{let resolve;const r=load('SharedResearchRecommendations','',[0,null],undefined,{rpc:()=>new Promise(done=>resolve=done)});r.exports.useSharedResearchRecommendations('all',0);const cleanup=r.effects[0]();cleanup();resolve({error:null,data:{contractVersion:1,generatedAt:'2026-10-07T02:00:00Z',items:researchItems}});await new Promise(done=>setTimeout(done,0));assert.equal(r.writes.length,0);const changed=load('SharedResearchRecommendations','',[0,{key:'all:0:0',payload:{items:researchItems},error:false}]);const value=changed.exports.useSharedResearchRecommendations('watched',1);assert.equal(value.payload,undefined);assert.equal(value.loading,true);});
test('status validator rejects non-mature checkpoint and mature blocker contradictions',()=>{const {exports}=render();for(const changes of [{asOf:'2026-10-07T00:00:00Z'},{status:'blocked',asOf:'2026-10-07T00:00:00Z'},{status:'matured',actionReturn:'0.125',asOf:'2026-10-07T00:00:00Z',blocker:'PINNED_EVIDENCE_REVISED'}]){const p={contractVersion:1,horizon:5,items:[{...status()[0],...changes}]};assert.equal(exports.validActionStatus(p,5),false);}});
test('dashboard Decision Lab branch renders only shared compact workspace',()=>{const source=fs.readFileSync(new URL('../components/MyDashboardClient.tsx',import.meta.url),'utf8');const ast=ts.createSourceFile('MyDashboardClient.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let branch;function visit(n){if(ts.isConditionalExpression(n)&&n.condition.getText(ast).replace(/\s+/g,'')==="selectedTab==='decision-lab'")branch=n.whenTrue;ts.forEachChild(n,visit);}visit(ast);assert.ok(branch);assert.match(branch.getText(ast),/SharedDecisionWorkspace/);assert.equal(/PredictionWorkspace|DecisionWorkspace|<h[12]/.test(branch.getText(ast).replace('SharedDecisionWorkspace','')),false);});
test('pending blocker and unsafe or absent blocked code are rejected',()=>{const {exports}=render();for(const changes of [{blocker:'PINNED_EVIDENCE_REVISED'},{status:'blocked',blocker:null},{status:'blocked',blocker:'Private exception https://secret.example'}])assert.equal(exports.validActionStatus({contractVersion:1,horizon:5,items:[{...status()[0],...changes}]},5),false);assert.equal(exports.validActionStatus({contractVersion:1,horizon:5,items:[{...status()[0],status:'blocked',blocker:'PINNED_EVIDENCE_REVISED'}]},5),true);});
