import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const migrationUrl = new URL('../supabase/migrations/20260903023351_my_dashboard_issuer_identity_v1.sql', import.meta.url)

test('issuer identity draft preserves canonical identity, applicability and provenance', async () => {
  const sql = await readFile(migrationUrl, 'utf8')
  assert.match(sql, /create table public\.canonical_issuers/)
  assert.match(sql, /issuer_key text not null/)
  assert.match(sql, /canonical_name text not null/)
  assert.match(sql, /issuer_key = lower\(btrim\(issuer_key\)\)/)
  assert.match(sql, /btrim\(canonical_name\) <> ''/)
  assert.match(sql, /issuer_key !~ '\[\[:space:\]\[:cntrl:\]\]'/)
  assert.match(sql, /canonical_name = btrim\(canonical_name\)/)
  assert.match(sql, /canonical_name !~ '\[\[:cntrl:\]\]'/)
  assert.match(sql, /entity_kind in \('corporate', 'fund_sponsor'\)/)
  assert.match(sql, /country_code is null or country_code ~ '\^\[A-Z\]\{2\}\$'/)
  assert.match(sql, /status in \('active', 'retired'\)/)
  assert.match(sql, /unique \(issuer_key\)/)
  assert.match(sql, /create function public\.set_canonical_issuers_updated_at\(\)/)
  assert.match(sql, /returns trigger/)
  assert.match(sql, /security invoker/)
  assert.match(sql, /set search_path = ''/)
  assert.match(sql, /new\.updated_at = clock_timestamp\(\)/)
  assert.match(sql, /create trigger canonical_issuers_set_updated_at/)
  assert.match(sql, /before update on public\.canonical_issuers/)
  assert.match(sql, /execute function public\.set_canonical_issuers_updated_at\(\)/)
  assert.doesNotMatch(sql, /execute function public\.set_trading_updated_at\(\)/)
  assert.match(sql, /create table public\.instrument_issuer_mappings/)
  assert.match(sql, /instrument_id uuid not null references public\.instruments\(id\) on delete cascade/)
  assert.match(sql, /issuer_id uuid references public\.canonical_issuers\(id\) on delete restrict/)
  assert.match(sql, /applicability in \('required', 'not_applicable'\)/)
  assert.match(sql, /applicability = 'required' and issuer_id is not null/)
  assert.match(sql, /applicability = 'not_applicable' and issuer_id is null/)
  assert.match(sql, /source_name text not null/)
  assert.match(sql, /source_name = btrim\(source_name\) and source_name <> ''/)
  assert.match(sql, /source_name !~ '\[\[:cntrl:\]\]'/)
  assert.match(sql, /source_url = btrim\(source_url\)/)
  assert.match(sql, /lower\(source_url\) like 'https:\/\/%'/)
  assert.match(sql, /split_part\(substring\(source_url from 9\), '\/', 1\) <> ''/)
  assert.match(sql, /strpos\(split_part\(substring\(source_url from 9\), '\/', 1\), '@'\) = 0/)
  assert.match(sql, /source_url !~ '\[\[:space:\]\[:cntrl:\]\]'/)
  assert.match(sql, /strpos\(source_url, '\?'\) = 0/)
  assert.match(sql, /strpos\(source_url, '#'\) = 0/)
  assert.match(sql, /evidence_as_of date not null/)
  assert.match(sql, /methodology_version text not null/)
  assert.match(sql, /methodology_version = btrim\(methodology_version\) and methodology_version <> ''/)
  assert.match(sql, /methodology_version !~ '\[\[:cntrl:\]\]'/)
  assert.match(sql, /valid_from date not null/)
  assert.match(sql, /valid_to date/)
  assert.match(sql, /valid_to is null or valid_to > valid_from/)
  assert.match(sql, /unique \(instrument_id, valid_from, methodology_version\)/)
  assert.match(sql, /create extension if not exists btree_gist with schema extensions/)
  assert.match(sql, /constraint instrument_issuer_mappings_validity_nonoverlap exclude using gist/)
  assert.match(sql, /instrument_id with =/)
  assert.match(sql, /daterange\(valid_from, valid_to, '\[\)'\) with &&/)
})

test('issuer identity draft is indexed and denied to browser roles', async () => {
  const sql = await readFile(migrationUrl, 'utf8')
  assert.match(sql, /create index instrument_issuer_mappings_issuer_id_idx/)
  assert.match(sql, /create unique index instrument_issuer_mappings_one_current_idx/)
  assert.match(sql, /where valid_to is null/)
  assert.match(sql, /create index instrument_issuer_mappings_instrument_validity_idx/)
  assert.match(sql, /alter table public\.canonical_issuers enable row level security/)
  assert.match(sql, /alter table public\.instrument_issuer_mappings enable row level security/)
  assert.match(sql, /alter table public\.canonical_issuers force row level security/)
  assert.match(sql, /alter table public\.instrument_issuer_mappings force row level security/)
  assert.match(sql, /revoke all on table public\.canonical_issuers from public, anon, authenticated/)
  assert.match(sql, /revoke all on table public\.instrument_issuer_mappings from public, anon, authenticated/)
  assert.match(sql, /grant select, insert, update, delete on table public\.canonical_issuers to service_role/)
  assert.match(sql, /grant select, insert, update, delete on table public\.instrument_issuer_mappings to service_role/)
  assert.match(sql, /revoke execute on function public\.set_canonical_issuers_updated_at\(\) from public, anon, authenticated/)
  assert.match(sql, /grant execute on function public\.set_canonical_issuers_updated_at\(\) to service_role/)
  assert.doesNotMatch(sql, /grant\s+[^;]+\s+to\s+(?:public|anon|authenticated)\b/i)
  assert.doesNotMatch(sql, /security\s+definer/i)
  assert.doesNotMatch(sql, /create policy/i)
})
