import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateSharedCallInDatabase,reconcileSharedEvaluation,SharedCommitUncertainError} from '../lib/shared-paper-db.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function snapshot(){return {contractVersion:1,asOf:'2026-09-02T18:00:00Z',call:{id:id(1),instrument_id:id(2),benchmark_instrument_id:id(3),provider_id:id(4),assessment_id:id(5),action:'WAIT',published_at:'2026-09-01T18:00:00Z',source_cutoff:'2026-09-01T17:00:00Z',model_identity:'fixture',thesis:'fixture',risks:'fixture',input_hash:'a'.repeat(64),currency:'USD',methodology:'shared-decision-lab-v1',cost_per_side:'0.001'},reviews:[],outcomes:[],observations:[],state:{call_id:id(1),version:'0',evaluated_through:null},instrumentExchange:'FIXTURE',benchmarkExchange:'FIXTURE',calendar:{exchange:'FIXTURE',complete:true,coverageStart:'2026-09-01T00:00:00Z',coverageEnd:'2026-09-04T00:00:00Z',provenance:{verified:true,verifiedAt:'2026-09-01T00:00:00Z',reference:'fixture',revision:'1'},sessions:[{id:'02',opens_at:'2026-09-02T09:00:00Z',closes_at:'2026-09-02T16:00:00Z'}]}};}
function client(fail){const queries=[];let receipt;return {queries,async query(sql,args){queries.push({sql,args});if(fail)await fail(sql,args);if(sql.startsWith('SELECT instrument'))return {rows:[{instrument_id:id(2)}]};if(sql.includes('snapshot_v1'))return {rows:[{payload:{snapshotToken:id(9),snapshot:snapshot()}}]};if(sql.includes('commit_shared')){const p=JSON.parse(args[2]);receipt={status:'COMMITTED',callId:p.callId,proposalHash:p.proposalHash,version:'1',evaluatedThrough:p.evaluatedThrough};return {rows:[{receipt}]};}if(sql.includes('receipt_v1'))return {rows:[{receipt:receipt??null}]};return {rows:[]};}};}
test('atomic watermark-only evaluation uses parameterized private RPCs and publisher lock',async()=>{const c=client();const result=await evaluateSharedCallInDatabase(c,id(1));assert.equal(result.proposal.added.length,0);assert.equal(c.queries[0].sql,'BEGIN ISOLATION LEVEL SERIALIZABLE');assert.equal(c.queries.at(-1).sql,'COMMIT');assert.ok(c.queries.find(q=>q.sql.includes('pg_advisory_xact_lock')));assert.equal(c.queries.filter(q=>q.sql.includes('commit_shared')).length,1);});
test('writer failure rolls back without retry',async()=>{const c=client(sql=>{if(sql.includes('commit_shared'))throw new Error('gate closed');});await assert.rejects(evaluateSharedCallInDatabase(c,id(1)),/gate closed/);assert.equal(c.queries.at(-1).sql,'ROLLBACK');assert.equal(c.queries.filter(q=>q.sql.includes('snapshot_v1')).length,1);});
test('commit uncertainty never retries and can reconcile exact receipt',async()=>{const c=client(sql=>{if(sql==='COMMIT')throw new Error('network lost');});let uncertain;try{await evaluateSharedCallInDatabase(c,id(1));}catch(e){uncertain=e;}assert.ok(uncertain instanceof SharedCommitUncertainError);assert.equal(c.queries.at(-1).sql,'COMMIT');assert.equal((await reconcileSharedEvaluation(c,uncertain)).status,'COMMITTED');const fresh=client();assert.equal((await reconcileSharedEvaluation(fresh,uncertain)).status,'UNRESOLVED');});
test('bad call ID never starts transaction',async()=>{const c=client();await assert.rejects(evaluateSharedCallInDatabase(c,'bad'));assert.equal(c.queries.length,0);});
test('rollback failure reports both causes',async()=>{const c=client(sql=>{if(sql.includes('snapshot_v1')||sql==='ROLLBACK')throw new Error(sql);});await assert.rejects(evaluateSharedCallInDatabase(c,id(1)),AggregateError);});
test('malformed writer acknowledgement rolls back',async()=>{const c=client();const query=c.query.bind(c);c.query=async(sql,args)=>sql.includes('commit_shared')?{rows:[{receipt:{status:'COMMITTED'}}]}:query(sql,args);await assert.rejects(evaluateSharedCallInDatabase(c,id(1)),/receipt/);assert.equal(c.queries.at(-1).sql,'ROLLBACK');});
