import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareSharedEvaluation,evaluateSharedCall,sharedSnapshotHash} from '../lib/shared-paper-adapter.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const callId=id(1),stock=id(2),benchmark=id(3),provider=id(4);
const event=(n,action,day)=>({id:id(n),call_id:callId,assessment_id:id(n+100),action,published_at:`2026-09-${day}T18:00:00Z`,source_cutoff:`2026-09-${day}T17:00:00Z`,model_identity:'fixture-only',thesis:'Synthetic evidence',risks:'Synthetic risks',input_hash:'a'.repeat(64)});
function fixture(){
 const sessions=['02','03','04'].map(day=>({id:day,opens_at:`2026-09-${day}T09:00:00Z`,closes_at:`2026-09-${day}T16:00:00Z`}));
 return {contractVersion:1,asOf:'2026-09-04T17:00:00Z',call:{...event(1,'BUY','01'),instrument_id:stock,benchmark_instrument_id:benchmark,provider_id:provider,currency:'USD',methodology:'shared-decision-lab-v1',cost_per_side:'0.001'},reviews:[event(5,'HOLD','02'),event(6,'SELL','03')],outcomes:[],state:{call_id:callId,version:'0',evaluated_through:null},instrumentExchange:'FIXTURE',benchmarkExchange:'FIXTURE',calendar:{exchange:'FIXTURE',complete:true,coverageStart:'2026-09-01T00:00:00Z',coverageEnd:'2026-09-05T00:00:00Z',provenance:{verified:true,verifiedAt:'2026-09-01T00:00:00Z',reference:'synthetic-calendar',revision:'1'},sessions},observations:sessions.flatMap((s,i)=>[stock,benchmark].map((instrument,j)=>({id:id(20+i*2+j),instrument_id:instrument,provider_id:provider,currency:'USD',interval_code:'1day',session_id:s.id,session_close:s.closes_at,loaded_at:s.closes_at,close:String(j?[200,202,204][i]:[100,105,110][i]),adjusted_close:String(j?[200,202,204][i]:[100,105,110][i])})))};
}
const receipt=p=>({status:'COMMITTED',callId:p.callId,proposalHash:p.proposalHash,version:String(BigInt(p.expectedVersion)+1n),evaluatedThrough:p.evaluatedThrough});
const persisted=p=>p.added.map((r,i)=>({...structuredClone(r),id:id(200+i),recorded_at:r.evidence.engine.recordedAt}));
test('deterministic BUY HOLD SELL maps schema and known net/benchmark returns',()=>{
 const s=fixture(),before=structuredClone(s),p=prepareSharedEvaluation(s);
 assert.deepEqual(s,before);assert.deepEqual(p,prepareSharedEvaluation(s));assert.equal(p.state,'Closed');
 const entry=p.added.find(r=>r.kind==='ENTRY'),exit=p.added.find(r=>r.kind==='EXIT');
 assert.equal(entry.price,'100');assert.equal(exit.price,'110');assert.ok(Math.abs(Number(exit.net_return)-.0978021978021979)<1e-12);assert.ok(Math.abs(Number(exit.benchmark_return)-.02)<1e-12);
 assert.equal(exit.call_id,callId);assert.equal(exit.evidence.calendarReference,'synthetic-calendar');assert.ok(Object.isFrozen(p.added));
});
test('canonical hashes ignore JSONB key ordering',()=>assert.equal(sharedSnapshotHash({a:1,b:{x:2,y:3}}),sharedSnapshotHash({b:{y:3,x:2},a:1})));
test('pinned outcomes survive reordered evidence and repeat evaluation adds none',()=>{
 const s=fixture(),p=prepareSharedEvaluation(s);s.outcomes=persisted(p);s.state={call_id:callId,version:'1',evaluated_through:s.asOf};
 for(const o of s.outcomes) if(o.evidence.engine.evidence) for(const k of ['stock','benchmark']) o.evidence.engine.evidence[k]=Object.fromEntries(Object.entries(o.evidence.engine.evidence[k]).reverse());
 const before=structuredClone(s.outcomes),next=prepareSharedEvaluation(s);assert.equal(next.added.length,0);assert.deepEqual(s.outcomes,before);assert.equal(next.state,'Closed');
});
for(const [name,change] of [
 ['unverified calendar',s=>s.calendar.provenance.verified=false],['incomplete calendar',s=>s.calendar.complete=false],['future calendar provenance',s=>s.calendar.provenance.verifiedAt='2026-10-01T00:00:00Z'],['future research',s=>s.call.source_cutoff='2026-10-01T00:00:00Z'],['future observation',s=>s.observations[0].loaded_at='2026-10-01T00:00:00Z'],['duplicate observation',s=>s.observations.push(s.observations[0])],['wrong currency',s=>s.observations[0].currency='AUD'],['wrong provider',s=>s.observations[0].provider_id=id(99)],['wrong session close',s=>s.observations[0].session_close='2026-09-02T15:00:00Z'],['rewound watermark',s=>s.state.evaluated_through='2026-10-01T00:00:00Z'],['unsupported decimal precision',s=>s.observations[0].close='100.1234567890123456']
]) test(`reject ${name}`,()=>{const s=fixture();change(s);assert.throws(()=>prepareSharedEvaluation(s));});
test('tampering with persisted numeric evidence rejects',()=>{const s=fixture();s.outcomes=persisted(prepareSharedEvaluation(s));s.state.evaluated_through=s.asOf;s.outcomes[0].price='999';assert.throws(()=>prepareSharedEvaluation(s),/mismatch/);});
test('persisted EXIT without ENTRY rejects',()=>{const s=fixture();s.outcomes=persisted(prepareSharedEvaluation(s)).filter(o=>o.kind!=='ENTRY');s.state.evaluated_through=s.asOf;assert.throws(()=>prepareSharedEvaluation(s));});
test('persisted entry event mismatch rejects',()=>{const s=fixture();s.outcomes=persisted(prepareSharedEvaluation(s));s.state.evaluated_through=s.asOf;s.outcomes.find(o=>o.kind==='ENTRY').evidence.engine.eventId=id(999);assert.throws(()=>prepareSharedEvaluation(s));});
test('checkpoint on wrong session rejects',()=>{const s=fixture();s.outcomes=persisted(prepareSharedEvaluation(s));s.state.evaluated_through=s.asOf;const r=structuredClone(s.outcomes.find(o=>o.kind==='MARK'));r.id=id(888);r.kind='CHECKPOINT_5';r.evidence.engine.kind=r.kind;r.evidence.engine.key=`${r.kind}:${r.evidence.engine.sessionId}`;s.outcomes.push(r);assert.throws(()=>prepareSharedEvaluation(s));});
test('performance before pinned entry rejects',()=>{const s=fixture();s.outcomes=persisted(prepareSharedEvaluation(s));s.state.evaluated_through=s.asOf;s.call.published_at='2026-09-02T18:00:00Z';s.call.source_cutoff='2026-09-02T17:00:00Z';s.reviews=s.reviews.filter(r=>r.action!=='HOLD');assert.throws(()=>prepareSharedEvaluation(s));});
test('persisted ENTRY and CANCELLED cannot coexist',()=>{const s=fixture();s.outcomes=persisted(prepareSharedEvaluation(s));s.state.evaluated_through=s.asOf;s.outcomes.push({id:id(999),call_id:callId,kind:'CANCELLED',as_of:'2026-09-02T08:00:00Z',recorded_at:s.asOf,price:null,net_return:null,benchmark_return:null,reason:'fixture',evidence:{engine:{kind:'CANCELLED',key:'CANCELLED:02',sessionId:'02',asOf:'2026-09-02T08:00:00Z',recordedAt:s.asOf,reason:'fixture',eventId:id(6)}}});assert.throws(()=>prepareSharedEvaluation(s));});
test('WAIT commits watermark with zero trade outcomes',async()=>{const s=fixture();s.call.action='WAIT';s.reviews=[];let commits=0;const r=await evaluateSharedCall(callId,{readSnapshot:async()=>s,commitProposal:async p=>{commits++;return receipt(p);}});assert.equal(commits,1);assert.equal(r.proposal.added.length,0);assert.equal(r.proposal.evaluatedThrough,s.asOf);});
test('explicit version conflict rereads and recomputes bounded fresh snapshot',async()=>{let reads=0,commits=0;const r=await evaluateSharedCall(callId,{readSnapshot:async()=>{const s=fixture();s.state.version=String(reads++);return s;},commitProposal:async p=>++commits===1?{status:'VERSION_CONFLICT'}:receipt(p)});assert.equal(reads,2);assert.equal(commits,2);assert.equal(r.proposal.expectedVersion,'1');});
test('conflict exhaustion stops at configured bound',async()=>{let commits=0;await assert.rejects(evaluateSharedCall(callId,{readSnapshot:async()=>fixture(),commitProposal:async()=>{commits++;return {status:'VERSION_CONFLICT'};}}),/retry limit/);assert.equal(commits,2);});
test('unknown commit failure never retries',async()=>{let reads=0,commits=0;await assert.rejects(evaluateSharedCall(callId,{readSnapshot:async()=>{reads++;return fixture();},commitProposal:async()=>{commits++;throw new Error('connection lost after commit');}}),/connection lost/);assert.equal(reads,1);assert.equal(commits,1);});
for(const [name,change] of [['identity',r=>r.callId=id(99)],['hash',r=>r.proposalHash='bad'],['version',r=>r.version='5'],['watermark',r=>r.evaluatedThrough='2026-01-01T00:00:00Z'],['unknown status',r=>r.status='UNKNOWN']]) test(`invalid receipt ${name} rejects without retry`,async()=>{let commits=0;await assert.rejects(evaluateSharedCall(callId,{readSnapshot:async()=>fixture(),commitProposal:async p=>{commits++;const r=receipt(p);change(r);return r;}}),/acknowledgement/);assert.equal(commits,1);});

